apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: demo-voting-app

spec:
  selector:
    name: redis-pod
    app: demo-voting-app
  ports:
      - targetPort: 6379
        port: 6379

